import Head from "next/head";

import localFont from "next/font/local";

import { useState } from "react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const [count, setCount] = useState(0);

  const increaseCount = () => {
    setCount(Math.abs(count + 1));
  };
  const decreaseCount = () => {
    setCount(Math.abs(count - 1));
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${geistSans.variable} ${geistMono.variable}`}>
        <main>
          <h1>{count}</h1>
          <button onClick={increaseCount}>Click</button>
          <button onClick={decreaseCount}>Click</button>
        </main>
      </div>
    </>
  );
}
